"use client";
import { Pulse as PPulse } from "@phosphor-icons/react/dist/csr/Pulse";
import { Bell as PBell } from "@phosphor-icons/react/dist/csr/Bell";
import { Check as PCheck } from "@phosphor-icons/react/dist/csr/Check";
import { WarningCircle as PWarningCircle } from "@phosphor-icons/react/dist/csr/WarningCircle";
import { Warning as PWarning } from "@phosphor-icons/react/dist/csr/Warning";
import { ChartBar as PChartBar } from "@phosphor-icons/react/dist/csr/ChartBar";
import { BookOpen as PBookOpen } from "@phosphor-icons/react/dist/csr/BookOpen";
import { Sparkle as PSparkle } from "@phosphor-icons/react/dist/csr/Sparkle";
import { Brain as PBrain } from "@phosphor-icons/react/dist/csr/Brain";
import { CheckCircle as PCheckCircle } from "@phosphor-icons/react/dist/csr/CheckCircle";
import { CheckSquare as PCheckSquare } from "@phosphor-icons/react/dist/csr/CheckSquare";
import { CaretDown as PCaretDown } from "@phosphor-icons/react/dist/csr/CaretDown";
import { CaretLeft as PCaretLeft } from "@phosphor-icons/react/dist/csr/CaretLeft";
import { CaretRight as PCaretRight } from "@phosphor-icons/react/dist/csr/CaretRight";
import { CaretUp as PCaretUp } from "@phosphor-icons/react/dist/csr/CaretUp";
import { Clock as PClock } from "@phosphor-icons/react/dist/csr/Clock";
import { Command as PCommand } from "@phosphor-icons/react/dist/csr/Command";
import { Cpu as PCpu } from "@phosphor-icons/react/dist/csr/Cpu";
import { Database as PDatabase } from "@phosphor-icons/react/dist/csr/Database";
import { DownloadSimple as PDownloadSimple } from "@phosphor-icons/react/dist/csr/DownloadSimple";
import { ArrowSquareOut as PArrowSquareOut } from "@phosphor-icons/react/dist/csr/ArrowSquareOut";
import { Eye as PEye } from "@phosphor-icons/react/dist/csr/Eye";
import { EyeSlash as PEyeSlash } from "@phosphor-icons/react/dist/csr/EyeSlash";
import { FileText as PFileText } from "@phosphor-icons/react/dist/csr/FileText";
import { FileCode as PFileCode } from "@phosphor-icons/react/dist/csr/FileCode";
import { Crosshair as PCrosshair } from "@phosphor-icons/react/dist/csr/Crosshair";
import { FolderSimple as PFolderSimple } from "@phosphor-icons/react/dist/csr/FolderSimple";
import { GitBranch as PGitBranch } from "@phosphor-icons/react/dist/csr/GitBranch";
import { Question as PQuestion } from "@phosphor-icons/react/dist/csr/Question";
import { Info as PInfo } from "@phosphor-icons/react/dist/csr/Info";
import { Key as PKey } from "@phosphor-icons/react/dist/csr/Key";
import { Laptop as PLaptop } from "@phosphor-icons/react/dist/csr/Laptop";
import { Stack as PStack } from "@phosphor-icons/react/dist/csr/Stack";
import { SquaresFour as PSquaresFour } from "@phosphor-icons/react/dist/csr/SquaresFour";
import { GridFour as PGridFour } from "@phosphor-icons/react/dist/csr/GridFour";
import { Lightbulb as PLightbulb } from "@phosphor-icons/react/dist/csr/Lightbulb";
import { LockSimple as PLockSimple } from "@phosphor-icons/react/dist/csr/LockSimple";
import { LockKey as PLockKey } from "@phosphor-icons/react/dist/csr/LockKey";
import { SignOut as PSignOut } from "@phosphor-icons/react/dist/csr/SignOut";
import { Envelope as PEnvelope } from "@phosphor-icons/react/dist/csr/Envelope";
import { List as PList } from "@phosphor-icons/react/dist/csr/List";
import { ChatText as PChatText } from "@phosphor-icons/react/dist/csr/ChatText";
import { Moon as PMoon } from "@phosphor-icons/react/dist/csr/Moon";
import { Graph as PGraph } from "@phosphor-icons/react/dist/csr/Graph";
import { Pause as PPause } from "@phosphor-icons/react/dist/csr/Pause";
import { ChartPieSlice as PChartPieSlice } from "@phosphor-icons/react/dist/csr/ChartPieSlice";
import { Play as PPlay } from "@phosphor-icons/react/dist/csr/Play";
import { Plus as PPlus } from "@phosphor-icons/react/dist/csr/Plus";
import { PlusCircle as PPlusCircle } from "@phosphor-icons/react/dist/csr/PlusCircle";
import { Printer as PPrinter } from "@phosphor-icons/react/dist/csr/Printer";
import { ArrowsClockwise as PArrowsClockwise } from "@phosphor-icons/react/dist/csr/ArrowsClockwise";
import { ArrowCounterClockwise as PArrowCounterClockwise } from "@phosphor-icons/react/dist/csr/ArrowCounterClockwise";
import { FloppyDisk as PFloppyDisk } from "@phosphor-icons/react/dist/csr/FloppyDisk";
import { MagnifyingGlass as PMagnifyingGlass } from "@phosphor-icons/react/dist/csr/MagnifyingGlass";
import { PaperPlaneTilt as PPaperPlaneTilt } from "@phosphor-icons/react/dist/csr/PaperPlaneTilt";
import { GearSix as PGearSix } from "@phosphor-icons/react/dist/csr/GearSix";
import { Shield as PShield } from "@phosphor-icons/react/dist/csr/Shield";
import { ShieldWarning as PShieldWarning } from "@phosphor-icons/react/dist/csr/ShieldWarning";
import { ShieldCheck as PShieldCheck } from "@phosphor-icons/react/dist/csr/ShieldCheck";
import { Sliders as PSliders } from "@phosphor-icons/react/dist/csr/Sliders";
import { SlidersHorizontal as PSlidersHorizontal } from "@phosphor-icons/react/dist/csr/SlidersHorizontal";
import { Sun as PSun } from "@phosphor-icons/react/dist/csr/Sun";
import { Terminal as PTerminal } from "@phosphor-icons/react/dist/csr/Terminal";
import { TrendDown as PTrendDown } from "@phosphor-icons/react/dist/csr/TrendDown";
import { TrendUp as PTrendUp } from "@phosphor-icons/react/dist/csr/TrendUp";
import { UploadSimple as PUploadSimple } from "@phosphor-icons/react/dist/csr/UploadSimple";
import { CloudArrowUp as PCloudArrowUp } from "@phosphor-icons/react/dist/csr/CloudArrowUp";
import { User as PUser } from "@phosphor-icons/react/dist/csr/User";
import { UserCheck as PUserCheck } from "@phosphor-icons/react/dist/csr/UserCheck";
import { UserCircle as PUserCircle } from "@phosphor-icons/react/dist/csr/UserCircle";
import { Users as PUsers } from "@phosphor-icons/react/dist/csr/Users";
import { X as PX } from "@phosphor-icons/react/dist/csr/X";
import { XCircle as PXCircle } from "@phosphor-icons/react/dist/csr/XCircle";
import { MagnifyingGlassPlus as PMagnifyingGlassPlus } from "@phosphor-icons/react/dist/csr/MagnifyingGlassPlus";
import { MagnifyingGlassMinus as PMagnifyingGlassMinus } from "@phosphor-icons/react/dist/csr/MagnifyingGlassMinus";
import { ArrowLeft as PArrowLeft } from "@phosphor-icons/react/dist/csr/ArrowLeft";
import { ArrowRight as PArrowRight } from "@phosphor-icons/react/dist/csr/ArrowRight";
import { ArrowUpRight as PArrowUpRight } from "@phosphor-icons/react/dist/csr/ArrowUpRight";
import { ArrowUp as PArrowUp } from "@phosphor-icons/react/dist/csr/ArrowUp";
import { ClockCounterClockwise as PClockCounterClockwise } from "@phosphor-icons/react/dist/csr/ClockCounterClockwise";
import { Copy as PCopy } from "@phosphor-icons/react/dist/csr/Copy";

import type { Icon, IconProps } from "@phosphor-icons/react";

// Preserve existing semantic names while using one consistent Phosphor family.
// Phosphor uses weight rather than SVG strokeWidth; regular is its balanced UI stroke.
function uiIcon(Component: Icon) {
  return function VaultIcon({
    strokeWidth: _strokeWidth,
    ...props
  }: IconProps & { strokeWidth?: number | string }) {
    void _strokeWidth;
    return (
      <Component size={18} weight="regular" aria-hidden="true" {...props} />
    );
  };
}

export const Activity = uiIcon(PPulse);
export const Bell = uiIcon(PBell);
export const Check = uiIcon(PCheck);
export const AlertCircle = uiIcon(PWarningCircle);
export const AlertTriangle = uiIcon(PWarning);
export const BarChart2 = uiIcon(PChartBar);
export const BookOpen = uiIcon(PBookOpen);
export const Bot = uiIcon(PSparkle);
export const Brain = uiIcon(PBrain);
export const CheckCircle2 = uiIcon(PCheckCircle);
export const CheckSquare = uiIcon(PCheckSquare);
export const ChevronDown = uiIcon(PCaretDown);
export const ChevronLeft = uiIcon(PCaretLeft);
export const ChevronRight = uiIcon(PCaretRight);
export const ChevronUp = uiIcon(PCaretUp);
export const Clock = uiIcon(PClock);
export const Command = uiIcon(PCommand);
export const Cpu = uiIcon(PCpu);
export const Database = uiIcon(PDatabase);
export const Download = uiIcon(PDownloadSimple);
export const ExternalLink = uiIcon(PArrowSquareOut);
export const Eye = uiIcon(PEye);
export const EyeOff = uiIcon(PEyeSlash);
export const FileCheck2 = uiIcon(PFileText);
export const FileJson = uiIcon(PFileCode);
export const FileText = uiIcon(PFileText);
export const Focus = uiIcon(PCrosshair);
export const FolderGit2 = uiIcon(PFolderSimple);
export const GitBranch = uiIcon(PGitBranch);
export const HelpCircle = uiIcon(PQuestion);
export const Info = uiIcon(PInfo);
export const KeyRound = uiIcon(PKey);
export const Laptop = uiIcon(PLaptop);
export const Layers = uiIcon(PStack);
export const LayoutDashboard = uiIcon(PSquaresFour);
export const LayoutGrid = uiIcon(PGridFour);
export const Lightbulb = uiIcon(PLightbulb);
export const Lock = uiIcon(PLockSimple);
export const LockKeyhole = uiIcon(PLockKey);
export const LogOut = uiIcon(PSignOut);
export const Mail = uiIcon(PEnvelope);
export const Menu = uiIcon(PList);
export const MessageSquare = uiIcon(PChatText);
export const Moon = uiIcon(PMoon);
export const Network = uiIcon(PGraph);
export const Pause = uiIcon(PPause);
export const PieChart = uiIcon(PChartPieSlice);
export const Play = uiIcon(PPlay);
export const Plus = uiIcon(PPlus);
export const PlusCircle = uiIcon(PPlusCircle);
export const Printer = uiIcon(PPrinter);
export const RefreshCw = uiIcon(PArrowsClockwise);
export const RotateCcw = uiIcon(PArrowCounterClockwise);
export const Save = uiIcon(PFloppyDisk);
export const Search = uiIcon(PMagnifyingGlass);
export const Send = uiIcon(PPaperPlaneTilt);
export const Settings = uiIcon(PGearSix);
export const Shield = uiIcon(PShield);
export const ShieldAlert = uiIcon(PShieldWarning);
export const ShieldCheck = uiIcon(PShieldCheck);
export const Sliders = uiIcon(PSliders);
export const SlidersHorizontal = uiIcon(PSlidersHorizontal);
export const Sparkles = uiIcon(PSparkle);
export const Sun = uiIcon(PSun);
export const Terminal = uiIcon(PTerminal);
export const TrendingDown = uiIcon(PTrendDown);
export const TrendingUp = uiIcon(PTrendUp);
export const Upload = uiIcon(PUploadSimple);
export const UploadCloud = uiIcon(PCloudArrowUp);
export const User = uiIcon(PUser);
export const UserCheck = uiIcon(PUserCheck);
export const UserRound = uiIcon(PUserCircle);
export const Users = uiIcon(PUsers);
export const X = uiIcon(PX);
export const XCircle = uiIcon(PXCircle);
export const ZoomIn = uiIcon(PMagnifyingGlassPlus);
export const ZoomOut = uiIcon(PMagnifyingGlassMinus);
export const ArrowLeft = uiIcon(PArrowLeft);
export const ArrowRight = uiIcon(PArrowRight);
export const ArrowUpRight = uiIcon(PArrowUpRight);

export const ArrowUp = uiIcon(PArrowUp);
export const ClockCounterClockwise = uiIcon(PClockCounterClockwise);
export const Sparkle = uiIcon(PSparkle);
export const Copy = uiIcon(PCopy);
